### ISSUE TITLE
To-Do List for v2.0

### ISSUE THREAD

**Issue by xosadmin** [xosadmin/cits5505Proj#6]
### Overview  
This is the to-do list for the v2.0 version. 
  
### Tasks  
- [x] Forget Password  
- [x] Modify Password and Pin code  
- [x] Ticketing system  
- [x] Pin code authentication  
- [x] Transform to SQLAlchemy  
- [x] Signs & Rewards System  
### Ideas  
None.

**Comment by xosadmin** [comment]
Since v2.0 has been released. This to-do list will be closed. Let's move to v3.0 to-do list.
